import {
  createSlice,
  createSelector,
  createEntityAdapter,
} from "@reduxjs/toolkit";

// This is the "state" for this slice. If initialState is an array, it should be treated
// as an array when using the "state" variable in reducers.
/* const initialState = {
  posts: [],
  status: "idle",
  error: null,
}; */

// Utilizing createEntityAdapter to allow for Redux to normalize data underneath the hood
// This will allow accessing posts using object key lookup instead of iterating over all posts
// And maintaining a seperate array of postIds to track updating and adding posts
// To prevent unnecessary re-renders when interacting with UI
const postsAdapter = createEntityAdapter({
  sortComparer: (a, b) => b.date.localeCompare(a.date),
});

const initialState = postsAdapter.getInitialState({
  status: "idle",
  error: null,
});

const postsSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
    postUpdated: (state, action) => {
      const { id, title, content } = action.payload;
      const existingPost = state.entities[id];
      if (existingPost) {
        existingPost.title = title;
        existingPost.content = content;
      }
    },
    reactionAdded: (state, action) => {
      const { postId, reaction } = action.payload;
      const existingPost = state.entities[postId];
      if (existingPost) {
        existingPost.reactions[reaction]++;
      }
    },
  },
});

//! Could change state.posts.posts to state.posts.items (in initialState) to avoid repetitive naming
/* export const selectAllPosts = (state) => state.posts.posts;

export const selectPostById = (state, postId) =>
  state.posts.posts.find((post) => post.id === postId); */

// This is a memoized selector function
// It utilizes a createSelector function (From the Reselect library, imported from RTK)
// Argument 1 are the "input selectors" that will grab returned results when selector is called and pass them to the output selector
// Argument 2 is the "output selector" that uses arguments generated by input selectors to calculate the returned state
// This memoized selector will only run if the arguments have changed, preventing unnecessary re-renders when the store is updated for other reasons

export const { postUpdated, reactionAdded } = postsSlice.actions;
export default postsSlice.reducer;
export const {
  selectAll: selectAllPosts,
  selectById: selectPostById,
  selectIds: selectPostIds,
} = postsAdapter.getSelectors((state) => state.posts);

export const selectPostsByUser = createSelector(
  [selectAllPosts, (state, userId) => userId],
  (posts, userId) => posts.filter((post) => post.user === userId)
);
